"""
Seed data module providing high-fidelity intelligence baselines across ecosystems,
sponsors, historical winners, active opportunities, and technical trends.
"""
from typing import List, Dict, Any

SEED_ECOSYSTEMS: List[Dict[str, Any]] = [
    {
        "slug": "solana",
        "name": "Solana",
        "category": "High-Performance L1",
        "momentum_score": 92.5,
        "momentum_trajectory": "↑",
        "breakdown_scores": {
            "developer_programs": 19.0,
            "hackathons_and_grants": 19.5,
            "dev_activity_acceleration": 14.5,
            "sdk_product_launches": 9.5,
            "sponsor_activity": 9.0,
            "social_discussion": 9.5,
            "funding_activity": 4.5,
            "competition_opportunity": 7.0
        },
        "tracked_repos": ["solana-labs/solana", "coral-xyz/anchor", "anza-xyz/agave"],
        "notes": "Massive developer flywheel driven by Colosseum Crypto World's Fair ($3.3M pool) and Blinks/Actions adoption."
    },
    {
        "slug": "base",
        "name": "Base",
        "category": "Ethereum L2",
        "momentum_score": 94.0,
        "momentum_trajectory": "↑",
        "breakdown_scores": {
            "developer_programs": 19.5,
            "hackathons_and_grants": 19.0,
            "dev_activity_acceleration": 15.0,
            "sdk_product_launches": 9.5,
            "sponsor_activity": 9.5,
            "social_discussion": 9.5,
            "funding_activity": 4.5,
            "competition_opportunity": 7.5
        },
        "tracked_repos": ["base-org", "coinbase/agentkit", "coinbase/x402"],
        "notes": "Leader in onchain consumer and autonomous agent micro-payments (x402, AgentKit, Base Batches, ERC-8021 builder codes)."
    },
    {
        "slug": "monad",
        "name": "Monad",
        "category": "Parallel EVM L1",
        "momentum_score": 88.0,
        "momentum_trajectory": "↑",
        "breakdown_scores": {
            "developer_programs": 18.0,
            "hackathons_and_grants": 18.5,
            "dev_activity_acceleration": 13.5,
            "sdk_product_launches": 9.0,
            "sponsor_activity": 8.0,
            "social_discussion": 9.5,
            "funding_activity": 4.5,
            "competition_opportunity": 7.0
        },
        "tracked_repos": ["monad-developers"],
        "notes": "Extreme developer anticipation leading up to mainnet; Nitro Accelerator ($500k) and Monad Momentum 1:1 token matching."
    },
    {
        "slug": "ethereum",
        "name": "Ethereum",
        "category": "L1 Settlement Layer",
        "momentum_score": 86.0,
        "momentum_trajectory": "→",
        "breakdown_scores": {
            "developer_programs": 17.0,
            "hackathons_and_grants": 18.0,
            "dev_activity_acceleration": 12.5,
            "sdk_product_launches": 8.5,
            "sponsor_activity": 9.5,
            "social_discussion": 8.5,
            "funding_activity": 4.0,
            "competition_opportunity": 8.0
        },
        "tracked_repos": ["ethereum/go-ethereum", "ethereum/EIPs"],
        "notes": "Highest aggregate prize liquidity and sponsor density via ETHGlobal circuits; mature but fiercely competitive."
    },
    {
        "slug": "arbitrum",
        "name": "Arbitrum",
        "category": "Ethereum L2",
        "momentum_score": 82.0,
        "momentum_trajectory": "→",
        "breakdown_scores": {
            "developer_programs": 16.0,
            "hackathons_and_grants": 16.5,
            "dev_activity_acceleration": 12.0,
            "sdk_product_launches": 8.5,
            "sponsor_activity": 8.5,
            "social_discussion": 8.0,
            "funding_activity": 4.0,
            "competition_opportunity": 8.5
        },
        "tracked_repos": ["OffchainLabs/nitro", "ArbitrumFoundation"],
        "notes": "Strong Stylus (Rust/C++ smart contracts) grant incentives and DeFi liquidity foundation."
    },
    {
        "slug": "sui",
        "name": "Sui",
        "category": "Move-based L1",
        "momentum_score": 84.5,
        "momentum_trajectory": "↑",
        "breakdown_scores": {
            "developer_programs": 17.5,
            "hackathons_and_grants": 17.0,
            "dev_activity_acceleration": 13.0,
            "sdk_product_launches": 8.5,
            "sponsor_activity": 8.0,
            "social_discussion": 8.5,
            "funding_activity": 4.5,
            "competition_opportunity": 7.5
        },
        "tracked_repos": ["MystenLabs/sui"],
        "notes": "Rapidly climbing TVL, object-centric model, included as dedicated track in Colosseum World's Fair."
    },
    {
        "slug": "megaeth",
        "name": "MegaETH",
        "category": "Real-Time EVM",
        "momentum_score": 85.0,
        "momentum_trajectory": "↑",
        "breakdown_scores": {
            "developer_programs": 17.0,
            "hackathons_and_grants": 16.0,
            "dev_activity_acceleration": 13.5,
            "sdk_product_launches": 9.0,
            "sponsor_activity": 8.0,
            "social_discussion": 9.5,
            "funding_activity": 4.0,
            "competition_opportunity": 8.0
        },
        "tracked_repos": ["megaeth-labs"],
        "notes": "Sub-millisecond latency focus; high dev attention for real-time finance, games, and autonomous agents."
    },
    {
        "slug": "decentralized-ai",
        "name": "Decentralized AI (Bittensor / Morpheus / Allora / Sentient)",
        "category": "AI x Crypto",
        "momentum_score": 93.0,
        "momentum_trajectory": "↑",
        "breakdown_scores": {
            "developer_programs": 19.0,
            "hackathons_and_grants": 18.5,
            "dev_activity_acceleration": 14.5,
            "sdk_product_launches": 9.5,
            "sponsor_activity": 9.0,
            "social_discussion": 10.0,
            "funding_activity": 4.5,
            "competition_opportunity": 8.0
        },
        "tracked_repos": ["opentensor/bittensor", "MorpheusAIs/Docs", "allora-network"],
        "notes": "Highest technical synergy with AI Platform Engineers; immense incentive capital moving toward verifiable inference and synthetic evaluation."
    }
]

SEED_SPONSORS: List[Dict[str, Any]] = [
    {
        "slug": "world",
        "name": "World (Worldcoin)",
        "ecosystem": "World Chain / Ethereum",
        "technology": "World ID, MiniKit, AgentKit, World Chain gasless relayer",
        "predictability_score": 94.0,
        "upcoming_likelihood": 96.0,
        "previous_hackathons": [
            "ETHGlobal Online 2026", "ETHGlobal Lisbon 2026",
            "ETHGlobal Brussels 2025", "ETHGlobal San Francisco 2025"
        ],
        "prize_amounts_total": 180000.0,
        "tracks": ["Best Mini App on World App", "Sybil Resistance via World ID", "AgentKit Verified Humans vs Autonomous Agents", "World Pool Prize"],
        "bounties": ["$5,000 Best MiniKit App", "$3,000 World ID Integration", "$2,000 AgentKit Agent Proof", "$2,500 World Pool"],
        "recurring_technologies": ["MiniKit SDK", "IDKit", "World Chain testnet/mainnet", "AgentKit"],
        "recurring_bounty_categories": ["Mini Apps", "Identity / Proof of Personhood", "AI Agent verification", "Social governance"],
        "common_winning_product_types": ["Consumer micro-apps with World App mobile UX", "Sybil-resistant voting/grant distribution", "AI agents backed by verified humans"],
        "features_frequently_used": ["MiniKit verify command", "World App deep linking", "World ID zero-knowledge proof verification"],
        "features_rarely_used": ["Cross-chain state proofs of World ID", "Complex server-side rate limiters with World ID nullifiers"],
        "oversaturated_ideas": ["Generic Sybil-resistant airdrop claimer", "Basic one-button World ID gated Discord bot"],
        "underserved_ideas": ["Agentic micro-escrows where AI agents negotiate on behalf of verified humans", "Privacy-preserving reputation portable across L2s using World ID nullifiers"],
        "integration_difficulty": "Low",
        "documentation_quality": "Exceptional",
        "typical_prize_distribution": "1st place: $5,000; 2nd place: $2,500; Pool: $2,500 split across all valid submissions",
        "historical_participation_rewards": "Pool prize awarded to almost all valid submissions that execute a verified proof",
        "repeat_sponsorship_frequency": "Appeared in 9 of the last 10 ETHGlobal hackathons",
        "recommended_preparation": "Clone MiniKit template, test local World ID simulator, wire AgentKit to an autonomous FastAPI agent."
    },
    {
        "slug": "dynamic",
        "name": "Dynamic",
        "ecosystem": "Multi-chain (EVM, Solana, Move)",
        "technology": "Embedded Wallets, Passkey Auth, Multi-chain Wallet SDK",
        "predictability_score": 89.0,
        "upcoming_likelihood": 88.0,
        "previous_hackathons": ["ETHGlobal Tokyo 2026", "ETHGlobal Lisbon 2026", "Solana Radar 2025"],
        "prize_amounts_total": 95000.0,
        "tracks": ["Best UX with Dynamic Embedded Wallets", "Cross-chain onboarding with Passkeys"],
        "bounties": ["$4,000 1st place best UX", "$2,000 2nd place", "$1,000 best mobile integration"],
        "recurring_technologies": ["@dynamic-labs/sdk-react-core", "@dynamic-labs/ethereum", "@dynamic-labs/solana"],
        "recurring_bounty_categories": ["UX / Account Abstraction", "Social Onboarding", "Cross-chain account linking"],
        "common_winning_product_types": ["Consumer web apps where users don't realize they are using crypto", "Split-key collaborative wallets"],
        "features_frequently_used": ["Passkey creation", "Social sign-in with Google/Twitter"],
        "features_rarely_used": ["Multi-wallet linking for cross-chain identity verification", "Programmatic session keys"],
        "oversaturated_ideas": ["Standard DeFi swap dashboard with Dynamic login button slapped on top"],
        "underserved_ideas": ["Autonomous AI agent delegation where user delegates session keys with strict spending limits via Dynamic"],
        "integration_difficulty": "Low",
        "documentation_quality": "Exceptional",
        "typical_prize_distribution": "$4,000 / $2,000 / $1,000",
        "historical_participation_rewards": "Dynamic swag package and API credits",
        "repeat_sponsorship_frequency": "High (frequent sponsor at tier 1 hackathons)",
        "recommended_preparation": "Install `@dynamic-labs/sdk-react-core` in frontend boilerplate, set up test API key in dashboard."
    },
    {
        "slug": "pyth-network",
        "name": "Pyth Network",
        "ecosystem": "Multi-chain (Solana, EVM, Move, Cosmos)",
        "technology": "Low-latency pull oracles, Pyth Entropy (VRF), Pyth Express Relay",
        "predictability_score": 92.0,
        "upcoming_likelihood": 90.0,
        "previous_hackathons": ["Colosseum Crypto World's Fair 2026", "ETHGlobal Cannes 2026", "Solana Renaissance 2025"],
        "prize_amounts_total": 120000.0,
        "tracks": ["Best Use of Pyth Pull Oracles", "Innovative Pyth Entropy application", "Best DeFi Liquidation / Auction with Express Relay"],
        "bounties": ["$5,000 Top Pyth Integration", "$3,000 Pyth Entropy Gaming / Lotteries", "$2,000 Express Relay"],
        "recurring_technologies": ["@pythnetwork/pyth-evm-js", "@pythnetwork/client", "Hermes Web Service"],
        "recurring_bounty_categories": ["DeFi Derivatives", "Perpetuals", "Prediction Markets", "Verifiable Randomness"],
        "common_winning_product_types": ["Sub-second perpetual DEXes", "Real-world data prediction markets", "Fair automated liquidation protocols"],
        "features_frequently_used": ["Hermes price update fetch", "pyth.updatePriceFeeds"],
        "features_rarely_used": ["Pyth Express Relay for MEV-resistant order execution", "Pyth Cross-chain benchmarks"],
        "oversaturated_ideas": ["Simple lending pool with Pyth oracle check", "Basic coin flip with Pyth Entropy"],
        "underserved_ideas": ["Automated algorithmic trading agents utilizing Pyth low-latency updates + x402 payment execution", "Dynamic synthetic risk hedging for GPU compute contracts"],
        "integration_difficulty": "Low",
        "documentation_quality": "Exceptional",
        "typical_prize_distribution": "$5k / $3k / $2k",
        "historical_participation_rewards": "Developer grants fast-track",
        "repeat_sponsorship_frequency": "Nearly universal in Solana and major EVM competitions",
        "recommended_preparation": "Review Pyth Hermes API endpoints; install `@pythnetwork/pyth-evm-js` in backend."
    }
]

SEED_WINNERS: List[Dict[str, Any]] = [
    {
        "id": "winner_agent_shield",
        "opportunity_id": "opp_ethglobal_tokyo_2026",
        "event_name": "ETHGlobal Brussels / Online",
        "project_name": "AgentShield Guard",
        "category": "AI Security / DevTools",
        "problem_solved": "AI agents draining smart contracts due to prompt injection or unconstrained execution",
        "product_category": "infra",
        "infra_vs_consumer": "Infrastructure",
        "frontend_quality": "High",
        "ux_quality": "High",
        "technical_depth": "Exceptional",
        "sponsor_integration_depth": "Deep",
        "originality": "High",
        "demo_quality": "Exceptional",
        "github_quality": "High",
        "number_of_integrations": 3,
        "ai_usage": True,
        "privacy_usage": False,
        "financial_use_case": True,
        "judges": "Top protocol engineers from Base, World, and Uniswap",
        "prize_won": "$12,000 across 3 tracks (1st World ID, 1st Base Track, Pool)",
        "repo_url": "https://github.com/agentshield/guard",
        "demo_url": "https://agentshield.dev",
        "winning_patterns": "Combined enterprise-grade agent guardrails (NeMo Guardrails) with onchain session spending caps and World ID human escalation.",
        "losing_patterns_identified": "Competitors submitted un-guarded chatbot wrappers that broke during live judge evaluations.",
        "oversaturated_category": False
    },
    {
        "id": "winner_micro_pay",
        "opportunity_id": "opp_colosseum_world_fair_2026",
        "event_name": "Colosseum Renaissance",
        "project_name": "FlowStream x402",
        "category": "Payments / AI Commerce",
        "problem_solved": "AI agents lacking standardized protocol to pay for per-token LLM inference and private API lookups",
        "product_category": "infra",
        "infra_vs_consumer": "Infrastructure",
        "frontend_quality": "High",
        "ux_quality": "Exceptional",
        "technical_depth": "Very High",
        "sponsor_integration_depth": "Deep",
        "originality": "Very High",
        "demo_quality": "Exceptional",
        "github_quality": "High",
        "number_of_integrations": 2,
        "ai_usage": True,
        "privacy_usage": False,
        "financial_use_case": True,
        "judges": "Solana Foundation Core Developers & Multicoin Capital partners",
        "prize_won": "$30,000 Grand Prize + Colosseum Accelerator Acceptance ($250k)",
        "repo_url": "https://github.com/flowstream/x402-solana",
        "demo_url": "https://flowstream.money",
        "winning_patterns": "Demonstrated live zero-friction sub-200ms payments directly from an autonomous Python agent without human intervention.",
        "losing_patterns_identified": "Traditional e-commerce dapps requiring manual Phantom wallet approval popups for every single request.",
        "oversaturated_category": False
    }
]

SEED_OPPORTUNITIES: List[Dict[str, Any]] = [
    {
        "id": "opp_colosseum_world_fair_2026",
        "name": "Colosseum Crypto World's Fair 2026",
        "slug": "colosseum-crypto-worlds-fair-2026",
        "type": "hackathon",
        "organizer": "Colosseum",
        "ecosystem": "Solana / Base / Ethereum / Sui / Zcash / Bitcoin / Tempo",
        "registration_open": True,
        "registration_deadline": "2026-10-10T23:59:59Z",
        "submission_deadline": "2026-10-12T23:59:59Z",
        "total_prize_usd": 3340000.0,
        "prize_breakdown": {
            "cash_prizes": 840000.0,
            "seed_funding": 2500000.0,
            "solana_track": 100000.0,
            "tempo_track": 100000.0,
            "base_track": 25000.0,
            "accelerator_pre_seed": 250000.0
        },
        "tracks": ["AI & Autonomous Agents", "Consumer & Payments", "DeFi & Capital Markets", "Infrastructure & DevTools", "Crypto World's Fair Grand Champion"],
        "sponsors": ["Solana Foundation", "Base", "Sui Foundation", "Tempo", "Zcash Community"],
        "participation_rewards": "Free RPC endpoints, priority access to Colosseum venture syndicate, and accelerator interview consideration.",
        "expected_competitors": 2200,
        "prize_to_competitor_ratio": 1518.18,
        "prob_placing": 0.22,
        "prob_any_reward": 0.38,
        "hack_score": 93.5,
        "skill_match_score": 92.0,
        "score_breakdown": {
            "reward_quality": 19.5,
            "competition_attractiveness": 17.5,
            "skill_fit": 14.5,
            "sponsor_history": 9.5,
            "ecosystem_momentum": 9.5,
            "prize_breadth": 9.5,
            "participation_rewards": 4.0,
            "startup_potential": 5.0,
            "portfolio_value": 4.5
        },
        "alert_level": 3,
        "status": "active",
        "url": "https://colosseum.com",
        "source_tier": "Tier 1",
        "source_url": "https://colosseum.com/announcements/crypto-worlds-fair",
        "tags": ["AI Agents", "x402", "Solana", "Base", "Accelerator", "Seed Funding"],
        "recommended_build_direction": "Autonomous Agent Gateway: Build an x402-native micro-inference proxy that uses your FastAPI + vLLM expertise to allow autonomous agents on Solana & Base to pay per-token with zero human popups, using your hackathon-launchpad UI for live agent telemetry.",
        "technologies_to_learn": ["x402 Solana signature format", "Tempo payment rails"]
    },
    {
        "id": "opp_ethglobal_tokyo_2026",
        "name": "ETHGlobal Tokyo 2026",
        "slug": "ethglobal-tokyo-2026",
        "type": "hackathon",
        "organizer": "ETHGlobal",
        "ecosystem": "Ethereum / L2s (Base, Arbitrum, Optimism)",
        "registration_open": True,
        "registration_deadline": "2026-09-24T23:59:59Z",
        "submission_deadline": "2026-09-27T14:00:00Z",
        "total_prize_usd": 150000.0,
        "prize_breakdown": {
            "main_pool": 25000.0,
            "sponsor_bounties": 125000.0
        },
        "tracks": ["Autonomous Agents", "Account Abstraction", "ZK & Verifiability", "Consumer Onboarding"],
        "sponsors": ["World", "Base", "Dynamic", "Uniswap Foundation", "Pyth Network", "EigenLayer"],
        "participation_rewards": "ETHGlobal staked refund + pooled sponsor bounties ($2,500 World Pool + Base builder credits)",
        "expected_competitors": 850,
        "prize_to_competitor_ratio": 176.47,
        "prob_placing": 0.28,
        "prob_any_reward": 0.55,
        "hack_score": 88.0,
        "skill_match_score": 89.0,
        "score_breakdown": {
            "reward_quality": 17.0,
            "competition_attractiveness": 16.5,
            "skill_fit": 14.0,
            "sponsor_history": 9.5,
            "ecosystem_momentum": 9.0,
            "prize_breadth": 9.0,
            "participation_rewards": 4.5,
            "startup_potential": 4.0,
            "portfolio_value": 4.5
        },
        "alert_level": 3,
        "status": "confirmed",
        "url": "https://ethglobal.com/events/tokyo2026",
        "source_tier": "Tier 2",
        "source_url": "https://ethglobal.com/events/tokyo2026",
        "tags": ["ETHGlobal", "World ID", "MiniKit", "Base", "Dynamic"],
        "recommended_build_direction": "World ID + AgentKit Guardian: Build a verifiable agent execution framework where AI agents run autonomous tasks via LangGraph/FastAPI, but cryptographically prove backing by a unique verified human with spending circuit-breakers.",
        "technologies_to_learn": ["World ID MiniKit SDK v2", "Base AgentKit Python bindings"]
    },
    {
        "id": "opp_base_retro_builder_grants_2026",
        "name": "Base Retroactive Builder Grants & Base Batches",
        "slug": "base-retroactive-builder-grants-2026",
        "type": "grant",
        "organizer": "Base Foundation",
        "ecosystem": "Base",
        "registration_open": True,
        "registration_deadline": "Ongoing",
        "submission_deadline": "Ongoing / Bi-weekly",
        "total_prize_usd": 500000.0,
        "prize_breakdown": {
            "retro_grants": "1 to 5 ETH per shipped project",
            "base_batches_investment": "$100,000 per selected team"
        },
        "tracks": ["AI Agents", "Trading & Payments (x402)", "Developer Tooling", "Consumer Onchain"],
        "sponsors": ["Base", "Coinbase Ventures"],
        "participation_rewards": "Direct developer recognition, Builder Codes (ERC-8021) revenue share, ecosystem co-marketing.",
        "expected_competitors": 450,
        "prize_to_competitor_ratio": 1111.11,
        "prob_placing": 0.35,
        "prob_any_reward": 0.60,
        "hack_score": 91.0,
        "skill_match_score": 94.0,
        "score_breakdown": {
            "reward_quality": 18.0,
            "competition_attractiveness": 18.5,
            "skill_fit": 14.5,
            "sponsor_history": 9.5,
            "ecosystem_momentum": 9.5,
            "prize_breadth": 8.0,
            "participation_rewards": 4.5,
            "startup_potential": 4.5,
            "portfolio_value": 4.0
        },
        "alert_level": 3,
        "status": "active",
        "url": "https://base.org/builders",
        "source_tier": "Tier 1",
        "source_url": "https://base.org/builders",
        "tags": ["Base", "Grants", "x402", "AgentKit", "Retroactive"],
        "recommended_build_direction": "Deploy an x402-gated open API using your existing FastAPI boilerplate, register the contract with an ERC-8021 Builder Code, and submit to the Base builder portal.",
        "technologies_to_learn": ["ERC-8021 Builder Codes specification"]
    },
    {
        "id": "opp_monad_metropolis_nitro",
        "name": "Monad Metropolis & Nitro Accelerator Cohort 2",
        "slug": "monad-metropolis-nitro-2026",
        "type": "accelerator",
        "organizer": "Monad Foundation",
        "ecosystem": "Monad",
        "registration_open": True,
        "registration_deadline": "2026-10-25T23:59:59Z",
        "submission_deadline": "2026-10-31T23:59:59Z",
        "total_prize_usd": 750000.0,
        "prize_breakdown": {
            "nitro_investment": 500000.0,
            "hackathon_prize_pool": 250000.0,
            "monad_momentum_matching": "1:1 token matching on retention"
        },
        "tracks": ["High-Frequency DeFi", "Autonomous AI Agents", "Consumer Micro-Transactions", "Developer Tooling"],
        "sponsors": ["Monad Labs", "Dragonfly", "Paradigm"],
        "participation_rewards": "Testnet priority faucet access, direct DevRel office hours, 1:1 Monad Momentum matching.",
        "expected_competitors": 950,
        "prize_to_competitor_ratio": 789.47,
        "prob_placing": 0.20,
        "prob_any_reward": 0.42,
        "hack_score": 89.5,
        "skill_match_score": 87.0,
        "score_breakdown": {
            "reward_quality": 19.0,
            "competition_attractiveness": 17.0,
            "skill_fit": 13.5,
            "sponsor_history": 8.5,
            "ecosystem_momentum": 9.5,
            "prize_breadth": 9.0,
            "participation_rewards": 4.0,
            "startup_potential": 5.0,
            "portfolio_value": 4.0
        },
        "alert_level": 3,
        "status": "active",
        "url": "https://monad.xyz/developers",
        "source_tier": "Tier 1",
        "source_url": "https://monad.xyz/developers",
        "tags": ["Monad", "Parallel EVM", "Nitro Accelerator", "DeFi", "AI Agents"],
        "recommended_build_direction": "High-Throughput Verifiable Agent Dispatcher: Exploit Monad's 10,000 TPS parallel EVM execution to build a real-time order-routing agent platform that executes 1,000 concurrent agent arbitrations.",
        "technologies_to_learn": ["Monad asynchronous execution semantics", "Foundry on Monad testnet"]
    },
    {
        "id": "opp_dorahacks_agent_economy",
        "name": "KeeperHub - The Agent Economy Hackathon",
        "slug": "keeperhub-agent-economy-2026",
        "type": "hackathon",
        "organizer": "DoraHacks",
        "ecosystem": "Multi-chain (EVM, Solana)",
        "registration_open": True,
        "registration_deadline": "2026-09-18T23:59:59Z",
        "submission_deadline": "2026-09-20T23:59:59Z",
        "total_prize_usd": 65000.0,
        "prize_breakdown": {
            "grand_prize": 20000.0,
            "track_prizes": 35000.0,
            "community_quadratic_voting": 10000.0
        },
        "tracks": ["Autonomous Agent Orchestration", "Agentic Wallets & Payment Protocols", "AI Eval & Guardrails"],
        "sponsors": ["KeeperHub", "Dora Grant DAO", "Allora Network"],
        "participation_rewards": "Quadratic funding pool distribution to all active projects with verified GitHub commits.",
        "expected_competitors": 280,
        "prize_to_competitor_ratio": 232.14,
        "prob_placing": 0.32,
        "prob_any_reward": 0.65,
        "hack_score": 85.5,
        "skill_match_score": 96.0,
        "score_breakdown": {
            "reward_quality": 16.0,
            "competition_attractiveness": 18.5,
            "skill_fit": 15.0,
            "sponsor_history": 8.0,
            "ecosystem_momentum": 9.0,
            "prize_breadth": 8.0,
            "participation_rewards": 4.5,
            "startup_potential": 3.5,
            "portfolio_value": 3.0
        },
        "alert_level": 3,
        "status": "active",
        "url": "https://dorahacks.io/hackathon/agent-economy",
        "source_tier": "Tier 2",
        "source_url": "https://dorahacks.io/hackathon/agent-economy",
        "tags": ["DoraHacks", "AI Agents", "Quadratic Funding", "Low Competition Edge"],
        "recommended_build_direction": "Multi-Agent Regression Harness: Package your existing Ragas/DeepEval and LangGraph evaluation engine with a FastAPI backend into an autonomous evaluator that benchmarks agent performance onchain.",
        "technologies_to_learn": ["KeeperHub task triggers"]
    }
]

SEED_TRENDS: List[Dict[str, Any]] = [
    {
        "id": "trend_x402_payments",
        "narrative_name": "x402 HTTP Micro-Payments for Autonomous AI Agents",
        "category": "AI x Crypto / Agentic Commerce",
        "discussion_velocity": 96.0,
        "repository_growth": 88.0,
        "grants_moving": 92.0,
        "description": "Standardized activation of HTTP 402 Payment Required for autonomous machine-to-machine commerce. AI agents pay per-request/per-token in under 200ms without human intervention.",
        "key_ecosystems": ["Base", "Solana", "Polygon", "Coinbase AgentKit"],
        "actionable_implications": "Integrate x402 payment receiver middleware into FastAPI services; judges at Colosseum, ETHGlobal, and Base actively seek implementations moving beyond toy chatbots into autonomous commerce."
    },
    {
        "id": "trend_verifiable_inference",
        "narrative_name": "Verifiable Onchain AI Inference & TEE Guardrails",
        "category": "AI Infrastructure / Security",
        "discussion_velocity": 89.0,
        "repository_growth": 84.0,
        "grants_moving": 90.0,
        "description": "Cryptographic and hardware attestation (TEEs, ZK proofs) proving that an LLM response was generated faithfully by a specific model without tampering.",
        "key_ecosystems": ["Decentralized AI", "EigenLayer", "Bittensor", "Morpheus", "Phala Network"],
        "actionable_implications": "Combines Staff AI Platform serving (vLLM, Ray Serve) with cryptographic verification. High grant potential across EigenLayer AVS programs."
    },
    {
        "id": "trend_parallel_evm",
        "narrative_name": "Parallel Execution EVM Chains (Monad / MegaETH)",
        "category": "Execution Layer Infrastructure",
        "discussion_velocity": 92.0,
        "repository_growth": 81.0,
        "grants_moving": 94.0,
        "description": "Pipelined parallel transaction execution achieving 10,000+ TPS and sub-second finality while preserving Ethereum bytecode compatibility.",
        "key_ecosystems": ["Monad", "MegaETH", "Sei"],
        "actionable_implications": "Build compute-heavy dapps that were previously impossible on Ethereum (high-frequency orderbooks, real-time agent multi-party games)."
    }
]
